apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mathserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mathserver
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 15
  # metrics:
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       averageUtilization: 50
